## Logistic Regression

Let's build a diabetes prediction model.

Here, you are going to predict diabetes using Logistic Regression Classifier.

You can find the dataset [here](https://www.kaggle.com/uciml/pima-indians-diabetes-database)

In [2]:
#import pandas
import pandas as pd
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']
# load dataset
pima = pd.read_csv('data/diabetes.csv', header=None, names=col_names)
pima = pima.drop(0)

In [3]:
pima.head()

  pregnant glucose  bp skin insulin   bmi pedigree age label
1        6     148  72   35       0  33.6    0.627  50     1
2        1      85  66   29       0  26.6    0.351  31     0
3        8     183  64    0       0  23.3    0.672  32     1
4        1      89  66   23      94  28.1    0.167  21     0
5        0     137  40   35     168  43.1    2.288  33     1

**Selecting Feature**


Lets divide the given columns into target variable and feature variables.

In [4]:
feature_cols = ['pregnant', 'insulin', 'bmi', 'age','glucose','bp','pedigree']
X = pima[feature_cols] # Features
y = pima.label # Target variable

Splitting Data

Remember we need to split our data into training and testing sets.

In [5]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

**Model Development and Prediction** 

First, import the Logistic Regression module and create a Logistic Regression classifier object using LogisticRegression() function.

Then, fit your model on the train set using fit() and perform prediction on the test set using predict().

In [6]:
# import the class
from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
logreg = LogisticRegression()

# fit the model with data
logreg.fit(X_train,y_train)

#
y_pred=logreg.predict(X_test)

/Users/seiryu8808/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

In [7]:
y_pred

array(['1', '0', '0', '1', '0', '0', '1', '1', '0', '0', '1', '1', '0',
       '0', '0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0',
       '0', '1', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0',
       '1', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0',
       '1', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0', '1', '1',
       '1', '1', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '1',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0',
       '0', '0', '0', '1', '0', '0', '1', '1', '0', '0', '0', '0', '0',
       '1', '0', '0', '0', '0', '1', '0', '0', '1', '0', '1', '1', '0',
       '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0',
       '0', '0', '0', '1', '0', '0', '0', '0', '1', '0', '0', '1', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0',
       '1', '0', '1', '1', '1', '1', '0', '0', '1', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '1',
       '0', '1', '1', '0', '1', '0', '0', '0', '0', '0'], dtype=object)

In [8]:
y_proba=logreg.predict_proba(X_test)
y_proba

array([[0.04919636, 0.95080364],
       [0.83865688, 0.16134312],
       [0.89274456, 0.10725544],
       [0.37371214, 0.62628786],
       [0.87265026, 0.12734974],
       [0.96215065, 0.03784935],
       [0.25919649, 0.74080351],
       [0.14772333, 0.85227667],
       [0.54048289, 0.45951711],
       [0.59484374, 0.40515626],
       [0.428596  , 0.571404  ],
       [0.03678218, 0.96321782],
       [0.69155128, 0.30844872],
       [0.76780816, 0.23219184],
       [0.86179699, 0.13820301],
       [0.83939765, 0.16060235],
       [0.16179634, 0.83820366],
       [0.9727441 , 0.0272559 ],
       [0.60589102, 0.39410898],
       [0.73481005, 0.26518995],
       [0.37117664, 0.62882336],
       [0.5567617 , 0.4432383 ],
       [0.75382506, 0.24617494],
       [0.93081654, 0.06918346],
       [0.9458559 , 0.0541441 ],
       [0.66514475, 0.33485525],
       [0.95522462, 0.04477538],
       [0.08841859, 0.91158141],
       [0.90158063, 0.09841937],
       [0.8605942 , 0.1394058 ],
       [0.53807962, 0.46192038],
       [0.75247054, 0.24752946],
       [0.8982701 , 0.1017299 ],
       [0.5259079 , 0.4740921 ],
       [0.90827877, 0.09172123],
       [0.31952429, 0.68047571],
       [0.58147546, 0.41852454],
       [0.924155  , 0.075845  ],
       [0.69098058, 0.30901942],
       [0.30815428, 0.69184572],
       [0.70159219, 0.29840781],
       [0.75415068, 0.24584932],
       [0.83632955, 0.16367045],
       [0.23500774, 0.76499226],
       [0.24958344, 0.75041656],
       [0.99323185, 0.00676815],
       [0.92671102, 0.07328898],
       [0.81694804, 0.18305196],
       [0.63671263, 0.36328737],
       [0.70194427, 0.29805573],
       [0.61877292, 0.38122708],
       [0.81523992, 0.18476008],
       [0.11526091, 0.88473909],
       [0.56754002, 0.43245998],
       [0.84058006, 0.15941994],
       [0.99668151, 0.00331849],
       [0.94122581, 0.05877419],
       [0.42902197, 0.57097803],
       [0.73432172, 0.26567828],
       [0.93577337, 0.06422663],
       [0.31563034, 0.68436966],
       [0.51813911, 0.48186089],
       [0.90270047, 0.09729953],
       [0.24550501, 0.75449499],
       [0.36177627, 0.63822373],
       [0.10538048, 0.89461952],
       [0.31392088, 0.68607912],
       [0.86699675, 0.13300325],
       [0.6194178 , 0.3805822 ],
       [0.88840193, 0.11159807],
       [0.87893117, 0.12106883],
       [0.58494476, 0.41505524],
       [0.90460301, 0.09539699],
       [0.04522844, 0.95477156],
       [0.1605671 , 0.8394329 ],
       [0.7059098 , 0.2940902 ],
       [0.87777019, 0.12222981],
       [0.37454025, 0.62545975],
       [0.92940568, 0.07059432],
       [0.82378043, 0.17621957],
       [0.64771111, 0.35228889],
       [0.62810633, 0.37189367],
       [0.78379878, 0.21620122],
       [0.97040248, 0.02959752],
       [0.8048265 , 0.1951735 ],
       [0.76735391, 0.23264609],
       [0.73324234, 0.26675766],
       [0.56794271, 0.43205729],
       [0.12820582, 0.87179418],
       [0.79308397, 0.20691603],
       [0.86625618, 0.13374382],
       [0.83718101, 0.16281899],
       [0.75399688, 0.24600312],
       [0.96135872, 0.03864128],
       [0.4057672 , 0.5942328 ],
       [0.82521436, 0.17478564],
       [0.53933018, 0.46066982],
       [0.48841944, 0.51158056],
       [0.32457799, 0.67542201],
       [0.74833692, 0.25166308],
       [0.71972022, 0.28027978],
       [0.90156213, 0.09843787],
       [0.78261732, 0.21738268],
       [0.96445214, 0.03554786],
       [0.36997071, 0.63002929],
       [0.61525065, 0.38474935],
       [0.87575555, 0.12424445],
       [0.75091594, 0.24908406],
       [0.96031236, 0.03968764],
       [0.28439821, 0.71560179],
       [0.89003558, 0.10996442],
       [0.69324094, 0.30675906],
       [0.39826003, 0.60173997],
       [0.60279472, 0.39720528],
       [0.46047842, 0.53952158],
       [0.41976918, 0.58023082],
       [0.86263745, 0.13736255],
       [0.33672531, 0.66327469],
       [0.91264041, 0.08735959],
       [0.22648618, 0.77351382],
       [0.64786185, 0.35213815],
       [0.63953343, 0.36046657],
       [0.71787154, 0.28212846],
       [0.56393725, 0.43606275],
       [0.81961178, 0.18038822],
       [0.95412567, 0.04587433],
       [0.66704507, 0.33295493],
       [0.65494301, 0.34505699],
       [0.49928229, 0.50071771],
       [0.6991458 , 0.3008542 ],
       [0.66019219, 0.33980781],
       [0.96599702, 0.03400298],
       [0.94336348, 0.05663652],
       [0.20357413, 0.79642587],
       [0.6701931 , 0.3298069 ],
       [0.60484274, 0.39515726],
       [0.8721681 , 0.1278319 ],
       [0.62573525, 0.37426475],
       [0.31876975, 0.68123025],
       [0.80210378, 0.19789622],
       [0.90718186, 0.09281814],
       [0.49404506, 0.50595494],
       [0.93440778, 0.06559222],
       [0.90743267, 0.09256733],
       [0.6471477 , 0.3528523 ],
       [0.91396414, 0.08603586],
       [0.92912837, 0.07087163],
       [0.9108987 , 0.0891013 ],
       [0.86104766, 0.13895234],
       [0.79904462, 0.20095538],
       [0.91753518, 0.08246482],
       [0.33791124, 0.66208876],
       [0.90510044, 0.09489956],
       [0.81945905, 0.18054095],
       [0.23114571, 0.76885429],
       [0.88174418, 0.11825582],
       [0.22827613, 0.77172387],
       [0.8550159 , 0.1449841 ],
       [0.44377074, 0.55622926],
       [0.0291314 , 0.9708686 ],
       [0.37651436, 0.62348564],
       [0.27842947, 0.72157053],
       [0.97783742, 0.02216258],
       [0.73925227, 0.26074773],
       [0.16346624, 0.83653376],
       [0.65949636, 0.34050364],
       [0.77614679, 0.22385321],
       [0.88373673, 0.11626327],
       [0.75866171, 0.24133829],
       [0.89496416, 0.10503584],
       [0.87382898, 0.12617102],
       [0.76824134, 0.23175866],
       [0.81749639, 0.18250361],
       [0.72403899, 0.27596101],
       [0.48341812, 0.51658188],
       [0.87208156, 0.12791844],
       [0.5580921 , 0.4419079 ],
       [0.89665637, 0.10334363],
       [0.89076324, 0.10923676],
       [0.93749012, 0.06250988],
       [0.8468543 , 0.1531457 ],
       [0.18300289, 0.81699711],
       [0.84232944, 0.15767056],
       [0.05036061, 0.94963939],
       [0.48152435, 0.51847565],
       [0.96777724, 0.03222276],
       [0.28862805, 0.71137195],
       [0.76074464, 0.23925536],
       [0.60270554, 0.39729446],
       [0.8540875 , 0.1459125 ],
       [0.81920083, 0.18079917],
       [0.91423515, 0.08576485]])

In [9]:
logreg.score(X_train, y_train)

0.7673611111111112

In [10]:
logreg.score(X_test, y_test)

0.8072916666666666

In [11]:
X_test.shape

(192, 7)

In [12]:
y_test

662    1
123    0
114    0
15     1
530    0
      ..
367    1
302    1
383    0
141    0
464    0
Name: label, Length: 192, dtype: object

In [15]:
y_df = pd.DataFrame(y_test)

In [16]:
#y_df

    label
662     1
123     0
114     0
15      1
530     0
..    ...
367     1
302     1
383     0
141     0
464     0

[192 rows x 1 columns]

In [17]:
X_df = X_test.merge(y_df, left_index=True, right_index=True).reset_index()
X_df

     index pregnant insulin   bmi age glucose  bp pedigree label
0      662        1       0  42.9  22     199  76    1.394     1
1      123        2     100  33.6  23     107  74    0.404     0
2      114        4       0    34  25      76  62    0.391     0
3       15        5     175  25.8  51     166  72    0.587     1
4      530        0       0  24.6  31     111  65     0.66     0
..     ...      ...     ...   ...  ..     ...  ..      ...   ...
187    367        6       0  27.6  29     124  72    0.368     1
188    302        2     135  31.6  25     144  58    0.422     1
189    383        1     182  25.4  21     109  60    0.947     0
190    141        3       0  21.1  55     128  78    0.268     0
191    464        5       0  27.6  37      88  78    0.258     0

[192 rows x 9 columns]

In [22]:
y_df2 = pd.DataFrame(y_pred, columns =['Predictions'])

In [23]:
X_df = X_df.merge(y_df2, left_index=True, right_index=True)

In [29]:
y_df3 = pd.DataFrame(y_proba[:,1], columns =['Proba'])
y_df3.shape

(192, 1)

In [30]:
X_df = X_df.merge(y_df3, left_index=True, right_index=True)
X_df

,index,pregnant,insulin,bmi,age,glucose,bp,pedigree,label,Predictions,Proba
0,662,1,0,42.9,22,199,76,1.394,1,1,0.950804
1,123,2,100,33.6,23,107,74,0.404,0,0,0.161343
2,114,4,0,34,25,76,62,0.391,0,0,0.107255
3,15,5,175,25.8,51,166,72,0.587,1,1,0.626288
4,530,0,0,24.6,31,111,65,0.66,0,0,0.127350
...,...,...,...,...,...,...,...,...,...,...,...
187,367,6,0,27.6,29,124,72,0.368,1,0,0.239255
188,302,2,135,31.6,25,144,58,0.422,1,0,0.397294
189,383,1,182,25.4,21,109,60,0.947,0,0,0.145913
190,141,3,0,21.1,55,128,78,0.268,0,0,0.180799
191,464,5,0,27.6,37,88,78,0.258,0,0,0.085765

**Model Evaluation using Confusion Matrix**  
A *confusion matrix* is a table that is used to evaluate the performance of a classification model. You can also visualize the performance of an algorithm. The fundamental of a confusion matrix is the number of correct and incorrect predictions are summed up class-wise.

In [20]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[117,  13],
       [ 24,  38]])

*There are more metrics in the tutorial. You do not need to do this for now as we will check them out next week.